### ISSUE TITLE
测试, 博主你好, 我使用会报错(评论与提交推送)

### ISSUE THREAD

**Issue by ThatCoders** [xaoxuu/issues-json-generator#4]
### 检查清单

- [X] 合法的、非营利性、无商业广告、无木马植入。
- [X] 有实质性原创内容的 HTTPS 站点，发布过至少 5 篇原创文章，内容题材不限。
- [X] 有独立域名，非免费域名。
- [x] 博客已运行至少半年，非刚搭建好。
- [ ] 与 **博主** 有至少 5 次有效互动（有内容的留言或者 issue 等）。

### 友链信息

```json
{
    "title": "无银百两",
    "url": "https://blog.giligili.work/",
    "avatar": "https://cdn.seclusion.work/blog/naive-ghost/logo/other/stack-128.gif",
}
```
![image](https://user-images.githubusercontent.com/43780818/213019438-e7357e48-6979-44db-8706-5540886528d1.png)
![image](https://user-images.githubusercontent.com/43780818/213019458-4e796df0-f42b-453a-9a57-ce20ed6f4737.png)

### 友链地址

https://giligili.work/friends.html

### 友链仓库（可选）

https://github.com/ThatCoders/friends-issues-json

**Comment by xaoxuu** [comment]
请提供一下报错对应的action链接，上面的链接404了

**Comment by ThatCoders** [comment]
> 请提供一下报错对应的action链接，上面的链接404了

https://github.com/ThatCoders/issues-json-generator/actions/runs/4032656183/jobs/6932674856

**Comment by xaoxuu** [comment]
> > 请提供一下报错对应的action链接，上面的链接404了
> 
> https://github.com/ThatCoders/issues-json-generator/actions/runs/4032656183/jobs/6932674856

这个我看你后面已经调通了，另外一个 https://github.com/ThatCoders/issues-json-generator/actions/runs/4033580689/jobs/6934197230 这个是没有权限

**Comment by lovelyJason** [comment]
为啥我构建后的output分支v2里面那个data.json是这样的
```json
{
  "version": "v2",
  "content": []
}
```

怎么content空的

**Comment by lovelyJason** [comment]
> 为啥我构建后的output分支v2里面那个data.json是这样的
> 
> ```json
> {
>   "version": "v2",
>   "content": []
> }
> ```
> 
> 怎么content空的

https://github.com/lovelyJason/issues-to-friends/actions/runs/8537763387
